#---------------------------------------
# Step C : Setup write PDF tool
#---------------------------------------

from langchain_core.tools import tool
from datetime import datetime
from pathlib import Path
import subprocess
import shutil
import re


# ----------------------------------------
# FIX 1: auto-wrap inline math expressions
# ----------------------------------------
def auto_math_wrap(text: str) -> str:
    """
    Automatically wraps common math-like expressions
    in inline LaTeX math mode ($...$) if missing.
    """
    patterns = [
        r"\b[A-Za-z]\_[A-Za-z0-9]+\b",     # x_i
        r"\b[A-Za-z]\^[A-Za-z0-9]+\b",     # x^2
        r"[A-Za-z]+\([A-Za-z0-9, ]+\)",    # f(x,y)
        r"[A-Za-z0-9]+\s*=\s*[A-Za-z0-9]+",# equations
    ]

    for p in patterns:
        text = re.sub(
            p,
            lambda m: f"${m.group(0)}$" if "$" not in m.group(0) else m.group(0),
            text,
        )

    return text


# ----------------------------------------
# FIX 2: sanitize LaTeX safely
# ----------------------------------------
def sanitize_latex(text: str) -> str:
    math_blocks = []

    def protect_math(match):
        math_blocks.append(match.group(0))
        return f"__MATH_{len(math_blocks)-1}__"

    # Protect math
    text = re.sub(r"\$\$.*?\$\$", protect_math, text, flags=re.S)
    text = re.sub(r"\$.*?\$", protect_math, text, flags=re.S)

    # Escape text
    text = text.replace("\\", r"\textbackslash{}")

    replacements = {
        "&": r"\&",
        "%": r"\%",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "^": r"\textasciicircum{}",
        "~": r"\textasciitilde{}",
    }

    for k, v in replacements.items():
        text = text.replace(k, v)

    # Restore math
    for i, block in enumerate(math_blocks):
        text = text.replace(f"__MATH_{i}__", block)

    return text


# ----------------------------------------
# FIX 3: normalize paragraphs
# ----------------------------------------
def normalize_linebreaks(text: str) -> str:
    lines = text.splitlines()
    return "\n".join(r"\par" if not line.strip() else line for line in lines)


# ----------------------------------------
# FIX 4: markdown → LaTeX
# ----------------------------------------
def markdown_to_latex(text: str) -> str:
    text = re.sub(r"^### (.*)", r"\\subsubsection{\1}", text, flags=re.M)
    text = re.sub(r"^## (.*)", r"\\subsection{\1}", text, flags=re.M)
    text = re.sub(r"^# (.*)", r"\\section{\1}", text, flags=re.M)
    return text


# ----------------------------------------
# FIX 5: LaTeX wrapper
# ----------------------------------------
def wrap_latex_body(body: str) -> str:
    return r"""
\documentclass[11pt]{article}
\usepackage{amsmath,amssymb}
\usepackage{hyperref}
\usepackage{geometry}
\geometry{margin=1in}

\usepackage{setspace}
\onehalfspacing
\usepackage{microtype}

\title{Statistical Modeling of Agentic Decision Dependencies}
\author{Generated by Research AI Agent}
\date{\today}

\begin{document}
\maketitle
""" + body + r"""
\end{document}
"""


@tool
def render_latex_pdf(latex_content: str) -> str:
    """
    Render a LaTeX document into a PDF file using Tectonic.

    Args:
        latex_content: Full LaTeX-compatible content of the research paper.

    Returns:
        Absolute path to the generated PDF file, or an error message.
    """
    if shutil.which("tectonic") is None:
        return "ERROR: tectonic is not installed."

    try:
        output_dir = Path("output").absolute()
        output_dir.mkdir(exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        tex_filename = f"paper_{timestamp}.tex"
        pdf_filename = f"paper_{timestamp}.pdf"

        tex_file = output_dir / tex_filename

        # ------------------------------
        # FINAL SAFE PIPELINE
        # ------------------------------
        content = latex_content.strip()

        content = auto_math_wrap(content)
        # 🔑 sanitize ONLY plain text, before LaTeX commands exist
        content = sanitize_latex(content)
        # 🔑 now safely convert markdown → LaTeX
        content = markdown_to_latex(content)
        # paragraph normalization last
        content = normalize_linebreaks(content)

        safe_latex = wrap_latex_body(content)

        tex_file.write_text(safe_latex, encoding="utf-8")

        result = subprocess.run(
            ["tectonic", tex_filename, "--outdir", str(output_dir)],
            cwd=output_dir,
            capture_output=True,
            text=True,
        )

        final_pdf = output_dir / pdf_filename

        if not final_pdf.exists():
            print("Tectonic STDOUT:\n", result.stdout)
            print("Tectonic STDERR:\n", result.stderr)
            return "ERROR: LaTeX compilation failed."

        return str(final_pdf)

    except Exception as e:
        return f"ERROR: {str(e)}"

